### ISSUE TITLE
Refund or owed??

### ISSUE THREAD

**Issue by witeshadow** [b-k/py1040#11]
I ran py1040 with test data and see this:

```
66.5 |                             Earned income credit (EIC) | 91.8
  74 |                                         Total payments | 91.8
  75 |                                                Refund! | 91.8
  78 |                                               Tax owed | 0
```

It makes it look like I have an EIC equal to my tax owed and yet also have a refund. 

This is not very clear. Shouldn't "Total payments" be indicated as negative?

**Comment by knasim** [comment]
also - it would be nice if this could generate a computer graph of all the forms required based on an individual.  sort of like a graphic that shows all the forms i.e. graph with vetices and edges.

**Comment by b-k** [comment]
For a graph, have a look at [1040.js](https://b-k.github.io/1040.js), which uses the same form database as this project. Commit 11d358173 redid the readme to directly point readers to 1040.js.

Regarding "total payments", we try to track the language on the 1040 (even when it's a little unintuitive), and that line expects a positive dollar amount. That line includes withheld taxes paid, and I think it would confuse users who made those sorts of payments to see them as negative.
