### ISSUE TITLE
is fica included

### ISSUE THREAD

**Issue by adnjoo** [b-k/py1040#15]
great code;

I tried comparing e.g. single W2 of $30,000 and got $1945 vs. $1942 for Federal taxes from [smartasset](https://smartasset.com/taxes/income-taxes)

but missing FICA and state (I tried California and got 4% marginal on 30k income) I think..

**Comment by b-k** [comment]
FICA is handled at the payroll level, not the 1040. It does appear on Schedule C, for example, but that form isn't implemented. I'm happy to lend a hand if you want to take the lead on implementation.

Regarding the $3 discrepancy, this may be a question of rounding. py1040 doesn't round, though tax rules advise rounding and some commercial calculators do so. Please reopen this issue if you trace through and find more-than-rounding errors.
