### ISSUE TITLE
name 'cell_list' is not defind

### ISSUE THREAD

**Issue by osama-synapse** [b-k/py1040#16]
I am facing this issue while running the app. 
[image](https://user-images.githubusercontent.com/94372156/144599589-bfdce2c3-8b09-4352-8ae5-8d48965ffb05.png)

**Comment by b-k** [comment]
I'm having trouble replicating this. Did the make script correctly download 1040.js, and were there any issues in generating `taxforms.py`? `cell_list` is defined in that file.

**Comment by osama-synapse** [comment]
I made a build using `make` and then I run the system. 
no files were missing.

**Comment by jjhamlin** [comment]
I ran into the same problem the first time I was trying to generate a Form 1040.  The problem was that when I ran `make` I did not have m4 installed.  After installing m4 and starting (completely from scratch) the error disappeared and everything worked.
