### ISSUE TITLE
Quick start instructions 

### ISSUE THREAD

**Issue by joelmacias** [b-k/py1040#5]
The Readme quick start instructions don't seem to work. 
After filling out interview.py and running taxes.py again I get the following error:

`Traceback (most recent call last):
  File "taxes.py", line 98, in <module>
    exec(open("taxforms.py").read())
FileNotFoundError: [Errno 2] No such file or directory: 'taxforms.py'`

I ran the make file then ran taxes.py again to see if it would fix the error, but then I got a new error: 

`Traceback (most recent call last):
  File "taxes.py", line 110, in <module>
    setup_inform(print_out=True)
  File "taxes.py", line 19, in setup_inform
    for i in cell_list.items():
NameError: name 'cell_list' is not defined`

This is the first time I submit an issue...hopefully i did it somewhat correctly.

**Comment by b-k** [comment]
Hi. I updated the project about 1.5 hours ago but forgot to fix the Readme until now.

The project now depends on the language-independent forms in the 1040.js project. Just run `make` to pull that project and produce taxforms.py.

Have updated the readme to indicate this extra step.
