### ISSUE TITLE
Show a screenshot of the shell output for the README?

### ISSUE THREAD

**Issue by dannguyen** [b-k/py1040#7]
The concept of this project is strong on its own but what immediately sold me on it was seeing this tweet:

https://twitter.com/konklone/status/711227705996550145

![image](https://cloud.githubusercontent.com/assets/121520/13940403/4b7658ce-ef9a-11e5-99aa-250a118964fa.png)

It should hook just about anyone who loves stdout, and more importantly, it gives some clue to the scope (and limitations) of the scripts without the user having to get their tax info out to test it.

**Comment by b-k** [comment]
An actual picture of what's going on...that never occurred to me.

Added at the head of Readme.md, as per your suggestion.
